# Generated by Django 5.2.4 on 2025-07-17 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='address',
            field=models.TextField(default='Add something of your own', help_text='Delivery address for medicines'),
        ),
    ]
