# Generated by Django 5.2.4 on 2025-07-17 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_userprofile_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='pincode',
            field=models.CharField(default='110001', help_text='Pincode for delivery', max_length=10),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='address',
            field=models.TextField(default='123 Main Street, Apartment 4B, City Center, New Delhi', help_text='Delivery address for medicines'),
        ),
    ]
