# Generated by Django 5.2.4 on 2025-07-17 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_userprofile_pincode_alter_userprofile_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('doctor', 'Doctor'), ('seller', 'Seller'), ('hospital_admin', 'Hospital Admin')], default='user', max_length=20),
        ),
    ]
