from django.contrib import admin
from django.urls import path
from . import views
urlpatterns=[
  path('',views.home_page,name='home'),
  path('doctors/',views.view_doctors,name='view_doctors'),
  path('hospital/<int:hospital_id>/doctors/', views.view_all_doctors, name='view_all_doctors'),
  path('add_review/<int:doctor_id>/',views.add_review,name='add_review'),
  path("doctor/<int:doctor_id>/",views.doctor_profile,name="doctor_profile"),
  path('hospital/<int:hospital_id>/doctor/<int:doctor_id>/appointments/', views.doctor_appointments, name='doctor_appointment'),
  path('get_available_timings/', views.get_available_timings, name='get_available_timings'),
  path('dashboard/me/', views.dashboard, name='user_dashboard'),
  path('cancel-appointment/<int:appointment_id>/', views.cancel_appointment, name='cancel_appointment'),
  path('reschedule-appointment/<int:appointment_id>/', views.reschedule_appointment, name='reschedule_appointment'),
  path('medicines/', views.medicines_page, name='medicines'),
  path('tests/', views.tests_page, name='tests_page'),
  path('add-medicine-to-cart/<int:medicine_id>/', views.add_medicine_to_cart, name='add_medicine_to_cart'),
  path('medicine-cart-checkout/', views.medicine_cart_checkout, name='medicine_cart_checkout'),
  path('process-medicine-payment/', views.process_medicine_payment, name='process_medicine_payment'),
  path('update-order-status/<int:order_id>/', views.update_order_status, name='update_order_status'),
  path('add-prescription/<int:appointment_id>/', views.add_prescription, name='add_prescription'),
  path('get-prescription-details/<int:appointment_id>/', views.get_prescription_details, name='get_prescription_details'),
  path('check-existing-appointments/', views.check_existing_appointments, name='check_existing_appointments'),
  path('doctor-take-leave/', views.doctor_take_leave, name='doctor_take_leave'),
  path('toggle-video-online/', views.toggle_video_online, name='toggle_video_online'),
  path('video-consultation/', views.video_consultation, name='video_consultation'),
  path('start-video-consultation/<int:doctor_id>/', views.start_video_consultation, name='start_video_consultation'),
  path('online-doctor-count/', views.online_doctor_count, name='online_doctor_count'),
  path('doctor-video-online-state/', views.doctor_video_online_state, name='doctor_video_online_state'),
  path('view-hospitals-for-testtype/<int:testtype_id>/', views.view_hospitals_for_testtype, name='view_hospitals_for_testtype'),
  path('add-to-cart/<int:test_id>/', views.add_to_cart, name='add_to_cart'),
  path('test-cart-checkout/', views.test_cart_checkout, name='test_cart_checkout'),
  path('process-test-payment/', views.process_test_payment, name='process_test_payment'),
  path('update-test-order-status/<int:order_id>/', views.update_test_order_status, name='update_test_order_status'),
  path('hospital-admin-home/', views.hospital_admin_home, name='hospital_admin_home'),
  path('add-test-for-hospital/', views.add_test_for_hospital, name='add_test_for_hospital'),
  path('create-test-report/<int:order_id>/', views.create_test_report, name='create_test_report'),
  path('approve-doctor-request/<int:request_id>/', views.approve_doctor_request, name='approve_doctor_request'),
  path('submit_symptoms/', views.submit_symptoms, name='submit_symptoms'),
  path('doctor-requests/', views.doctor_requests_page, name='doctor_requests'),
  path('update-appointment-status/', views.update_appointment_status, name='update_appointment_status'),
  path('get-appointment-status/<int:appointment_id>/', views.get_appointment_status, name='get_appointment_status'),
  path('video-consultation/<int:room_id>/', views.video_consultation, name='video_consultation_room'),
]
