# Generated by Django 4.2.4 on 2023-08-21 20:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hospitals.state')),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='profile_pic/DoctorProfilePic/')),
                ('address', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=20)),
                ('department', models.CharField(choices=[('Cardiology', 'Cardiology'), ('Orthopedics', 'Orthopedics'), ('Dermatology', 'Dermatology'), ('Pediatrics', 'Pediatrics'), ('Obstetrics and Gynecology', 'Obstetrics and Gynecology'), ('Neurology', 'Neurology'), ('Ophthalmology', 'Ophthalmology'), ('ENT (Ear, Nose, and Throat)', 'ENT (Ear, Nose, and Throat)')], default='Cardiology', max_length=30)),
                ('status', models.BooleanField(default=True)),
                ('hospitals', models.ManyToManyField(related_name='doctors', to='Hospitals.hospital')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
