# Generated by Django 3.2.7 on 2023-10-02 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospitals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='location',
            field=models.CharField(default='Kolkata', max_length=80),
        ),
        migrations.DeleteModel(
            name='Doctor',
        ),
    ]
