# Generated by Django 5.2.4 on 2025-07-16 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospitals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='video_online',
            field=models.BooleanField(default=False),
        ),
    ]
