# Generated by Django 3.2.7 on 2023-10-03 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospitals', '0002_auto_20231002_1734'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=30)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='profile_pic/DoctorProfilePic/')),
                ('mobile', models.CharField(max_length=20)),
                ('department', models.CharField(choices=[('Cardiology', 'Cardiology'), ('Orthopedics', 'Orthopedics'), ('Dermatology', 'Dermatology'), ('Pediatrics', 'Pediatrics'), ('Obstetrics and Gynecology', 'Obstetrics and Gynecology'), ('Neurology', 'Neurology'), ('Ophthalmology', 'Ophthalmology'), ('ENT (Ear, Nose, and Throat)', 'ENT (Ear, Nose, and Throat)')], default='Cardiology', max_length=30)),
                ('status', models.BooleanField(default=True)),
                ('hospitals', models.ManyToManyField(related_name='doctors', to='Hospitals.Hospital')),
            ],
        ),
    ]
