# Generated by Django 5.2.4 on 2025-07-16 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospitals', '0002_doctor_video_online'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('sample_required', models.CharField(blank=True, help_text='Type of sample required, e.g. blood, urine', max_length=100)),
                ('available', models.BooleanField(default=True)),
                ('included_tests', models.CharField(blank=True, help_text='Comma-separated list of included test names (for packages)', max_length=1000)),
                ('package_discount', models.DecimalField(blank=True, decimal_places=2, help_text='Discount percentage for the package, if applicable', max_digits=5, null=True)),
                ('pre_test_instructions', models.TextField(blank=True, help_text='Instructions for the patient before taking the test or package')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='Hospitals.hospital')),
            ],
        ),
    ]
