# Generated by Django 5.2.4 on 2025-07-16 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospitals', '0003_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('sample_required', models.CharField(blank=True, help_text='Type of sample required, e.g. blood, urine', max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='test',
            name='description',
        ),
        migrations.RemoveField(
            model_name='test',
            name='included_tests',
        ),
        migrations.RemoveField(
            model_name='test',
            name='name',
        ),
        migrations.RemoveField(
            model_name='test',
            name='sample_required',
        ),
        migrations.AddField(
            model_name='test',
            name='test_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hospital_tests', to='Hospitals.testtype'),
        ),
    ]
