# Generated by Django 3.2.7 on 2023-10-04 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospitals', '0004_hospital_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='hospital_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pic/HospitalPic/'),
        ),
    ]
