# Generated by Django 5.2.4 on 2025-07-16 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospitals', '0004_testtype_remove_test_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testtype',
            name='description',
        ),
        migrations.AddField(
            model_name='test',
            name='test_included',
            field=models.CharField(blank=True, help_text='Comma-separated list of included test names (for packages)', max_length=1000),
        ),
    ]
