# Generated by Django 5.2.4 on 2025-07-16 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospitals', '0005_remove_testtype_description_test_test_included'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testtype',
            name='sample_required',
            field=models.CharField(blank=True, choices=[('blood', 'Blood'), ('urine', 'Urine'), ('saliva', 'Saliva'), ('stool', 'Stool'), ('swab', 'Swab')], help_text='Type of sample required', max_length=20),
        ),
    ]
