# Generated by Django 5.2.4 on 2025-07-17 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospitals', '0007_medicineorder_medicineorderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicineorder',
            name='delivery_pincode',
            field=models.CharField(default='110001', max_length=10),
        ),
        migrations.AlterField(
            model_name='medicineorder',
            name='delivery_address',
            field=models.TextField(default='123 Main Street, Apartment 4B, City Center, New Delhi'),
        ),
    ]
