# Generated by Django 3.2.7 on 2023-10-04 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospitals', '0009_alter_hospital_hospital_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='qualifications',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='hospital_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pic/HospitalPic/'),
        ),
    ]
