# Generated by Django 5.2.4 on 2025-07-17 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hospitals', '0009_medicineorder_razorpay_order_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicineorder',
            name='razorpay_order_id',
        ),
        migrations.RemoveField(
            model_name='medicineorder',
            name='razorpay_payment_id',
        ),
    ]
