# Generated by Django 5.2.4 on 2025-07-17 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospitals', '0011_testorder_testorderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='testtype',
            name='preferred_time_slots',
            field=models.JSONField(blank=True, default=list, help_text='Allowed time slots for this test. Leave blank for all slots.'),
        ),
    ]
