# Generated by Django 5.2.4 on 2025-07-17 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospitals', '0012_testtype_preferred_time_slots'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hospital',
            old_name='location',
            new_name='address',
        ),
        migrations.AddField(
            model_name='hospital',
            name='latitude',
            field=models.FloatField(default=22.5744),
        ),
        migrations.AddField(
            model_name='hospital',
            name='longitude',
            field=models.FloatField(default=88.3629),
        ),
    ]
