# Generated by Django 3.2.7 on 2023-10-06 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospitals', '0013_alter_review_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='rating',
            field=models.BigIntegerField(default=3),
        ),
    ]
