# Generated by Django 5.2.4 on 2025-07-17 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospitals', '0013_rename_location_hospital_address_hospital_latitude_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('findings_positive', models.TextField(blank=True, verbose_name='Positive Findings')),
                ('findings_negative', models.TextField(blank=True, verbose_name='Negative Findings')),
                ('report_file', models.FileField(blank=True, null=True, upload_to='test_reports/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_to_patient', models.BooleanField(default=False)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='Hospitals.testorder')),
            ],
        ),
    ]
