# Generated by Django 5.2.4 on 2025-07-17 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospitals', '0015_doctorhospitalrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoappointment',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='video_appointments', to='Hospitals.doctor'),
        ),
    ]
