# Generated by Django 3.2.7 on 2023-10-13 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hospitals', '0016_appointment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['appointment_date', 'time']},
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='end_time',
            new_name='time',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='start_time',
        ),
    ]
