# Generated by Django 5.2.4 on 2025-07-18 05:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospitals', '0016_alter_videoappointment_doctor'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrescriptionTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, help_text='Additional notes or instructions for the test')),
                ('priority', models.CharField(choices=[('routine', 'Routine'), ('urgent', 'Urgent'), ('emergency', 'Emergency')], default='routine', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='Hospitals.prescription')),
                ('test_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hospitals.testtype')),
            ],
        ),
    ]
