# Generated by Django 5.2.4 on 2025-07-18 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospitals', '0017_prescriptiontest'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicineorderitem',
            name='prescription_proof',
            field=models.FileField(blank=True, null=True, upload_to='medicine_prescription_proofs/'),
        ),
    ]
