# Generated by Django 3.2.7 on 2023-10-13 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hospitals', '0017_auto_20231013_0525'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='day_of_week',
        ),
    ]
