# Generated by Django 5.2.4 on 2025-07-18 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospitals', '0018_medicineorderitem_prescription_proof'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='video_appointment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prescription', to='Hospitals.videoappointment'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='appointment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prescription', to='Hospitals.appointment'),
        ),
    ]
