# Generated by Django 3.2.7 on 2023-10-13 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospitals', '0018_remove_appointment_day_of_week'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
