# Generated by Django 3.2.7 on 2023-10-13 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hospitals', '0019_appointment_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['-appointment_date', '-time']},
        ),
    ]
