# Generated by Django 5.2.4 on 2025-07-14 18:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospitals', '0021_alter_appointment_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine', models.CharField(max_length=100)),
                ('dosage', models.PositiveIntegerField()),
                ('dosage_unit', models.CharField(default='Tablet(s)', max_length=20)),
                ('num_days', models.PositiveIntegerField()),
                ('num_days_unit', models.CharField(default='Day', max_length=20)),
                ('frequency', models.CharField(max_length=50)),
                ('route', models.CharField(max_length=50)),
                ('food_relation', models.CharField(blank=True, max_length=50)),
                ('instruction', models.CharField(blank=True, max_length=255)),
                ('diagnosis', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prescription', to='Hospitals.appointment')),
            ],
        ),
    ]
