# Generated by Django 5.2.4 on 2025-07-14 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospitals', '0022_prescription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='dosage',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='dosage_unit',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='food_relation',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='frequency',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='instruction',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='medicine',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='num_days',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='num_days_unit',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='route',
        ),
        migrations.CreateModel(
            name='MedicineEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine', models.CharField(max_length=100)),
                ('dosage', models.PositiveIntegerField()),
                ('dosage_unit', models.CharField(default='Tablet(s)', max_length=20)),
                ('num_days', models.PositiveIntegerField()),
                ('num_days_unit', models.CharField(default='Day', max_length=20)),
                ('frequency', models.CharField(max_length=50)),
                ('route', models.CharField(max_length=50)),
                ('food_relation', models.CharField(blank=True, max_length=50)),
                ('instruction', models.CharField(blank=True, max_length=255)),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicines', to='Hospitals.prescription')),
            ],
        ),
    ]
