# Generated by Django 5.2.4 on 2025-07-14 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hospitals', '0023_remove_prescription_dosage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicineentry',
            name='instruction',
        ),
        migrations.RemoveField(
            model_name='medicineentry',
            name='route',
        ),
    ]
