# Generated by Django 5.2.4 on 2025-07-15 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospitals', '0025_medicine'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='medicine_pics/'),
        ),
    ]
