# Generated by Django 5.2.4 on 2025-07-15 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospitals', '0026_medicine_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='cure_to',
            field=models.CharField(choices=[('Body Pain', 'Body Pain'), ('Diabetes', 'Diabetes'), ('Fever', 'Fever'), ('Cold', 'Cold'), ('Hypertension', 'Hypertension'), ('Allergy', 'Allergy'), ('Asthma', 'Asthma'), ('Other', 'Other')], default='Body Pain', max_length=30),
        ),
    ]
