# Generated by Django 5.2.4 on 2025-07-15 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hospitals', '0027_medicine_cure_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicineentry',
            name='num_days_unit',
        ),
    ]
