# Generated by Django 5.2.4 on 2025-07-15 08:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospitals', '0028_remove_medicineentry_num_days_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicineentry',
            name='medicine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hospitals.medicine'),
        ),
    ]
