# Generated by Django 5.2.4 on 2025-07-16 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospitals', '0030_doctorleave'),
    ]

    operations = [
        migrations.AddField(
            model_name='timing',
            name='max_capacity',
            field=models.PositiveIntegerField(default=10, help_text='Maximum number of appointments allowed in this time slot'),
        ),
    ]
