# Generated by Django 5.2.4 on 2025-07-16 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospitals', '0031_timing_max_capacity'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='timing',
            constraint=models.CheckConstraint(condition=models.Q(('start_time__lt', models.F('end_time'))), name='timing_start_before_end'),
        ),
    ]
